
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app


## dao生成
#gen:
#  dao:
#    - link:            "mysql:root:root@tcp(127.0.0.1:3306)/shop"
#      removePrefix:    "gf_"
#      descriptionTag:  true
#      noModelComment:  true


database:
  default:
    host:          "127.0.0.1"
    port:          "3306"
    user:          "root"
    pass:          "root"
    name:          "shop"
    type:          "mysql"
    debug:         "true"