
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app


## dao生成
#gen:
#  dao:
#    - link:            "mysql:root:root@tcp(127.0.0.1:3306)/shop"
#      removePrefix:    "gf_"
#      descriptionTag:  true
#      noModelComment:  true


database:
  default:
    host:          "127.0.0.1"
    port:          "3306"
    user:          "root"
    pass:          "root"
    name:          "shop2"
    type:          "mysql"
    debug:         "true"
    extra: loc=local

# Redis 配置示例
redis:
  # 单实例配置示例1
  default:
    address: 127.0.0.1:6377
    db: 1
    pass: szj123456
    idleTimeout: 600

upload:
  path: "upload"

qiniu:
  bucket: "goofyimg"  # 七牛云存储空间名
  accessKey: "zyeI_gv-qWUoSQVO_7XxGo2OJrPrfPBLGzJhi9hX"
  secretKey: "zyeI_gv-qWUoSQVO_7XxGo2OJrPrfPBLGzJhi9hX"
  url: "shyfvg5t4.hn-bkt.clouddn.com" #域名